- name: Cloning Dotfiles
  ansible.builtin.git:
    repo: "git@github.com:otatski/dotfiles.git"
    dest: "{{ home }}/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: config_v2
