- name: Install kitty
  shell: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin

- name: Checking if ~/.local/bin exists
  stat:
    path: "~/.local/bin/"
  register: local_bin

- name: Creating ~/.local/bin
  shell: mkdir ~/.local/bin/
  when: not local_bin.stat.exists

- name: Add kitty desktop integration
  shell: |
    ln -s ~/.local/kitty.app/bin/kitty ~/.local/bin/
    sed -i "s|Icon=kitty|Icon=/home/$USER/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" ~/.local/share/applications/kitty*.desktop
    sed -i "s|Exec=kitty|Exec=/home/$USER/.local/kitty.app/bin/kitty|g" ~/.local/share/applications/kitty*.desktop
