- name: Checking if neovim config is present
  stat:
    path: /home/{{ lookup('env', 'USER') }}/.config/nvim
    register: nvim_config_check

- name: Backup old neovim config
  shell: mv ~/.config/nvim ~/.config/nvim.bak
  when: nvim_config_check.stat.exists

- name: Add neovim config
  ansible.builtin.git:
    repo: "https://github.com/AstroNvim/AstroNvim.git"
    dest: ~/dotfiles/nvim/.config/nvim
    clone: yes

- name: Copy user config files for neovim
  shell: |
    cp -r ~/dotfiles/.nvim_config/user ~/dotfiles/nvim/.config/nvim/lua
    nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
