- name: Checking if neovim config is present
  stat:
    path: {{home}}/.config/nvim
  register: nvim_check

- name: Backup old neovim config
  shell: mv {{home}}/.config/nvim ~/.config/nvim.bak
  when: nvim_check.stat.exists

- name: Check if neovim config is in dotfiles
  stat:
    path: {{home}}/dotfiles/nvim/.config/nvim
  register: nvim_dotfile_check

- name: Delete old nvim config
  shell: rm -rf {{home}}/dotfiles/nvim/.config/nvim
  when: nvim_dotfile_check.stat.exists

- name: Check if neovim site files exist
  stat:
    path: {{home}}/.local/share/nvim/site
  register: nvim_site_check

- name: Delete old neovim site files
  shell: rm -rf {{home}}/.local/share/nvim/site
  when: nvim_site_check.stat.exists

- name: Add AstroNvim to dotfiles
  shell: |
    git clone https://github.com/AstroNvim/AstroNvim.git
    mv AstroNvim {{home}}/dotfiles/nvim/.config/nvim

- name: Copy user config files for neovim
  shell: |
    cp -r {{home}}/dotfiles/.nvim_config/user {{home}}/dotfiles/nvim/.config/nvim/lua
