- name: Install neovim from source
  become: true
  shell: |
    wget https://github.com/neovim/neovim/releases/download/v0.7.2/nvim-linux64.deb -P /tmp
    sudo dpkg -i /tmp/nvim-linux64.deb
    rm /tmp/nvim-linux64.deb

# - name: Install neovim
#   become: true
#   apt:
#     name: neovim
#     state: present

#- name: Install Terminal Text Editors
#  become: true
#  apt:
#    name: [vim]
